#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.1
#  in conjunction with Tcl version 8.6
#    Apr 24, 2020 07:03:52 PM CST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def clean():
    '''
    此处为点击【清除】按钮后的逻辑
    点击清除文本框以及词云
    '''
    w.Text1.delete('1.0', 'end')
    sys.stdout.flush()

def creat_menu():
    '''
    此处为点击【生成菜谱】按钮后的逻辑
    从 csv 中随机抽取三菜一汤
    显示在文本框
    显示词云在标签栏
    '''
    import pandas as pd
    import numpy as np
    import wordcloud

    menu_df = pd.read_csv('foods.csv', encoding='utf8')
    soup_df = pd.read_csv('soups.csv', encoding='utf8')

    # DataFrame 转化为 list
    menus = menu_df.sample(3)
    menus = np.array(menus)
    menus = menus.tolist()
    soup = soup_df.sample()
    soup = np.array(soup)
    soup = soup.tolist()

    # 合并【三菜一汤】
    menus.extend(soup)

    # 制作菜单的文本，保存食材词
    text = ''
    word = '、'
    for i in range(len(menus)):
        txt = '''菜名：{}\n食材：{}\n评分：{}\n制作方法：{}\n\n'''
        txt = txt.format(menus[i][0], menus[i][1], menus[i][2], menus[i][3])
        text += txt
        word += menus[i][1]

    # 菜单文本框插入
    w.Text1.insert('insert',text)

    # 词云生成
    word = word.replace('、', ' ')
    wd = wordcloud.WordCloud(background_color='white',
                            width=478, height=181,
                            font_path='msyh.ttc',
                            )
    wd.generate(word)
    wd.to_file('foods.png')

    # 插入词云
    img = tk.PhotoImage(file='foods.png')
    w.Label1.configure(imag=img).pack()

    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import ui
    ui.vp_start_gui()




